# Generated by Django 5.1.4 on 2025-01-07 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "max_length": "El nombre no puede ser mayor a 30 caracteres",
                            "required": "Este campo es requerido",
                        },
                        max_length=30,
                        verbose_name="Nombre de Platillo",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        error_messages={
                            "max_value": "El precio no puede ser mayor a 1,000",
                            "min_value": "El precio no puede ser menor a 0",
                            "required": "Este campo es requerido",
                        },
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="Precio de Platillo",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        error_messages={
                            "max_value": "La cantidad no puede ser mayor a 1,000",
                            "min_value": "La cantidad no puede ser menor a 0",
                        },
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="Cantidad de Platillo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Editado"),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
