# Generated by Django 5.1.4 on 2024-12-24 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dish_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="quantity",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Cantidad de Platillo",
            ),
        ),
    ]
