# Generated by Django 5.1.4 on 2025-01-01 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dish_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.ImageField(
                error_messages={
                    "empty": "El archivo seleccionado está vacío",
                    "invalid": "El archivo seleccionado no es una imagen",
                    "invalid_image": "El archivo seleccionado no es una imagen válida",
                    "missing": "No se ha seleccionado ningún archivo",
                    "required": "Este campo es requerido",
                },
                upload_to="dishes_image/",
                verbose_name="Imagen de Platillo",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(
                error_messages={
                    "max_length": "El nombre no puede ser mayor a 30 caracteres",
                    "required": "Este campo es requerido",
                },
                max_length=30,
                verbose_name="Nombre de Platillo",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.IntegerField(
                error_messages={
                    "max_value": "El precio no puede ser mayor a 1,000",
                    "min_value": "El precio no puede ser menor a 0",
                    "required": "Este campo es requerido",
                },
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Precio de Platillo",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="quantity",
            field=models.IntegerField(
                blank=True,
                default=0,
                error_messages={
                    "max_value": "La cantidad no puede ser mayor a 1,000",
                    "min_value": "La cantidad no puede ser menor a 0",
                },
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Cantidad de Platillo",
            ),
        ),
    ]
