# Generated by Django 5.1.4 on 2025-01-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dish_management", "0004_alter_dish_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="image",
        ),
    ]
